package com.example.model

data class EvolutionStageInfo(
    val stage: Int,
    val nameRu: String,
    val subtitleRu: String,
    val pslScore: Double,
    val reqAura: Double,
    val clickMultiplier: Double,
    val passiveMultiplier: Double,
    val description: String,
    val memeQuote: String,
    val profileFeature: String
)

object EvolutionStages {
    val STAGES = listOf(
        EvolutionStageInfo(
            stage = 0,
            nameRu = "Подзаборный Сойджак",
            subtitleRu = "Level 0: Subfive (PSL 1.5)",
            pslScore = 1.5,
            reqAura = 0.0,
            clickMultiplier = 1.0,
            passiveMultiplier = 1.0,
            description = "Рот открыт, шея согнута вперед от телефона.",
            memeQuote = "«Брат, зачем мьюить, генетика решает...»",
            profileFeature = "Скошенный подбородок"
        ),
        EvolutionStageInfo(
            stage = 1,
            nameRu = "Случайный Нормис",
            subtitleRu = "Level 1: Normie (PSL 2.0)",
            pslScore = 2.0,
            reqAura = 500.0,
            clickMultiplier = 1.5,
            passiveMultiplier = 1.2,
            description = "Закрыл рот и выпрямил шею.",
            memeQuote = "«Я просто умылся холодной водой!»",
            profileFeature = "Базовая осанка"
        ),
        EvolutionStageInfo(
            stage = 2,
            nameRu = "Адепт Утреннего Льда",
            subtitleRu = "Level 2: Ice Dipper (PSL 2.5)",
            pslScore = 2.5,
            reqAura = 1500.0,
            clickMultiplier = 2.0,
            passiveMultiplier = 1.5,
            description = "Лицо в таз со льдом каждое утро.",
            memeQuote = "«Холод сужает поры и пробуждает зверя!»",
            profileFeature = "Уменьшенная отечность"
        ),
        EvolutionStageInfo(
            stage = 3,
            nameRu = "Гуаша Практик",
            subtitleRu = "Level 3: Gua Sha User (PSL 3.0)",
            pslScore = 3.0,
            reqAura = 3500.0,
            clickMultiplier = 2.5,
            passiveMultiplier = 1.8,
            description = "Каменный скребок скользит по скулам.",
            memeQuote = "«Каждый вечер 20 минут лимфодренажа.»",
            profileFeature = "Первые контуры скул"
        ),
        EvolutionStageInfo(
            stage = 4,
            nameRu = "Новичок Мьюинга",
            subtitleRu = "Level 4: Mewing Novice (PSL 3.5)",
            pslScore = 3.5,
            reqAura = 8000.0,
            clickMultiplier = 3.2,
            passiveMultiplier = 2.2,
            description = "Язык прижат к нёбу.",
            memeQuote = "«Не могу говорить, язык прижат к нёбу!»",
            profileFeature = "Поднятая подъязычная кость"
        ),
        EvolutionStageInfo(
            stage = 5,
            nameRu = "Турник-Дрочила",
            subtitleRu = "Level 5: Pullup Starter (PSL 4.0)",
            pslScore = 4.0,
            reqAura = 18000.0,
            clickMultiplier = 4.0,
            passiveMultiplier = 2.8,
            description = "Широкий хват и подтягивания до подбородка.",
            memeQuote = "«Делай базу, пацан, спина будет треугольником.»",
            profileFeature = "V-образная фигура"
        ),
        EvolutionStageInfo(
            stage = 6,
            nameRu = "Креатиновый Натиск",
            subtitleRu = "Level 6: Creatine Surge (PSL 4.3)",
            pslScore = 4.3,
            reqAura = 35000.0,
            clickMultiplier = 5.0,
            passiveMultiplier = 3.5,
            description = "5 грамм креатина моногидрата в день.",
            memeQuote = "«Мышцы залило водой, сила прёт!»",
            profileFeature = "Наполненные челюстные мышцы"
        ),
        EvolutionStageInfo(
            stage = 7,
            nameRu = "Охотник за Солнцем",
            subtitleRu = "Level 7: Sun-Gazer (PSL 4.6)",
            pslScore = 4.6,
            reqAura = 65000.0,
            clickMultiplier = 6.2,
            passiveMultiplier = 4.2,
            description = "SPF 100 и получение витамина D.",
            memeQuote = "«Кожа как у римского гладиатора.»",
            profileFeature = "Золотистый тон кожи"
        ),
        EvolutionStageInfo(
            stage = 8,
            nameRu = "Острый Подбородок",
            subtitleRu = "Level 8: Sharp Chin (PSL 4.9)",
            pslScore = 4.9,
            reqAura = 110000.0,
            clickMultiplier = 7.5,
            passiveMultiplier = 5.0,
            description = "Жевательная резинка Mastic Gum каждый день.",
            memeQuote = "«Челюсть хрустит, но растет вширь!»",
            profileFeature = "Сформированный подбородок"
        ),
        EvolutionStageInfo(
            stage = 9,
            nameRu = "Ученик Охотника",
            subtitleRu = "Level 9: Hunter Eye Pupil (PSL 5.2)",
            pslScore = 5.2,
            reqAura = 180000.0,
            clickMultiplier = 9.0,
            passiveMultiplier = 6.0,
            description = "Взгляд исподлобья и прищур.",
            memeQuote = "«Не моргай при разговоре с фоидками.»",
            profileFeature = "Уменьшенное верхнее веко"
        ),
        EvolutionStageInfo(
            stage = 10,
            nameRu = "Перспективный Чадлайт",
            subtitleRu = "Stage 10: PSL 5.5",
            pslScore = 5.5,
            reqAura = 300000.0,
            clickMultiplier = 11.0,
            passiveMultiplier = 7.5,
            description = "Ступень эволюции луксмаксинга #10. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 10: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 10/100, PSL 5.5"
        ),
        EvolutionStageInfo(
            stage = 11,
            nameRu = "Перспективный Чадлайт • Фаза 2",
            subtitleRu = "Stage 11: PSL 5.6",
            pslScore = 5.6,
            reqAura = 395852.0,
            clickMultiplier = 12.4,
            passiveMultiplier = 8.4,
            description = "Ступень эволюции луксмаксинга #11. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 11: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 11/100, PSL 5.6"
        ),
        EvolutionStageInfo(
            stage = 12,
            nameRu = "Перспективный Чадлайт • Фаза 3",
            subtitleRu = "Stage 12: PSL 5.7",
            pslScore = 5.7,
            reqAura = 522330.0,
            clickMultiplier = 13.8,
            passiveMultiplier = 9.3,
            description = "Ступень эволюции луксмаксинга #12. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 12: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 12/100, PSL 5.7"
        ),
        EvolutionStageInfo(
            stage = 13,
            nameRu = "Перспективный Чадлайт • Фаза 4",
            subtitleRu = "Stage 13: PSL 5.8",
            pslScore = 5.8,
            reqAura = 689219.0,
            clickMultiplier = 15.2,
            passiveMultiplier = 10.2,
            description = "Ступень эволюции луксмаксинга #13. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 13: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 13/100, PSL 5.8"
        ),
        EvolutionStageInfo(
            stage = 14,
            nameRu = "Перспективный Чадлайт • Фаза 5",
            subtitleRu = "Stage 14: PSL 5.9",
            pslScore = 5.9,
            reqAura = 909430.0,
            clickMultiplier = 16.6,
            passiveMultiplier = 11.1,
            description = "Ступень эволюции луксмаксинга #14. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 14: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 14/100, PSL 5.9"
        ),
        EvolutionStageInfo(
            stage = 15,
            nameRu = "Гониальный Мастер 90°",
            subtitleRu = "Stage 15: PSL 6.0",
            pslScore = 6.0,
            reqAura = 1200000.0,
            clickMultiplier = 18.0,
            passiveMultiplier = 12.0,
            description = "Ступень эволюции луксмаксинга #15. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 15: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 15/100, PSL 6.0"
        ),
        EvolutionStageInfo(
            stage = 16,
            nameRu = "Гониальный Мастер 90° • Фаза 2",
            subtitleRu = "Stage 16: PSL 6.1",
            pslScore = 6.1,
            reqAura = 1563103.0,
            clickMultiplier = 20.0,
            passiveMultiplier = 13.2,
            description = "Ступень эволюции луксмаксинга #16. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 16: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 16/100, PSL 6.1"
        ),
        EvolutionStageInfo(
            stage = 17,
            nameRu = "Гониальный Мастер 90° • Фаза 3",
            subtitleRu = "Stage 17: PSL 6.2",
            pslScore = 6.2,
            reqAura = 2036075.0,
            clickMultiplier = 22.0,
            passiveMultiplier = 14.4,
            description = "Ступень эволюции луксмаксинга #17. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 17: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 17/100, PSL 6.2"
        ),
        EvolutionStageInfo(
            stage = 18,
            nameRu = "Гониальный Мастер 90° • Фаза 4",
            subtitleRu = "Stage 18: PSL 6.3",
            pslScore = 6.3,
            reqAura = 2652162.0,
            clickMultiplier = 24.0,
            passiveMultiplier = 15.6,
            description = "Ступень эволюции луксмаксинга #18. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 18: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 18/100, PSL 6.3"
        ),
        EvolutionStageInfo(
            stage = 19,
            nameRu = "Гониальный Мастер 90° • Фаза 5",
            subtitleRu = "Stage 19: PSL 6.4",
            pslScore = 6.4,
            reqAura = 3454668.0,
            clickMultiplier = 26.0,
            passiveMultiplier = 16.8,
            description = "Ступень эволюции луксмаксинга #19. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 19: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 19/100, PSL 6.4"
        ),
        EvolutionStageInfo(
            stage = 20,
            nameRu = "Коч Братан (Street Mogger)",
            subtitleRu = "Stage 20: PSL 6.5",
            pslScore = 6.5,
            reqAura = 4500000.0,
            clickMultiplier = 28.0,
            passiveMultiplier = 18.0,
            description = "Ступень эволюции луксмаксинга #20. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 20: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 20/100, PSL 6.5"
        ),
        EvolutionStageInfo(
            stage = 21,
            nameRu = "Коч Братан (Street Mogger) • Фаза 2",
            subtitleRu = "Stage 21: PSL 6.6",
            pslScore = 6.6,
            reqAura = 5725168.0,
            clickMultiplier = 30.8,
            passiveMultiplier = 19.6,
            description = "Ступень эволюции луксмаксинга #21. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 21: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 21/100, PSL 6.6"
        ),
        EvolutionStageInfo(
            stage = 22,
            nameRu = "Коч Братан (Street Mogger) • Фаза 3",
            subtitleRu = "Stage 22: PSL 6.7",
            pslScore = 6.7,
            reqAura = 7283901.0,
            clickMultiplier = 33.6,
            passiveMultiplier = 21.2,
            description = "Ступень эволюции луксмаксинга #22. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 22: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 22/100, PSL 6.7"
        ),
        EvolutionStageInfo(
            stage = 23,
            nameRu = "Коч Братан (Street Mogger) • Фаза 4",
            subtitleRu = "Stage 23: PSL 6.8",
            pslScore = 6.8,
            reqAura = 9267013.0,
            clickMultiplier = 36.4,
            passiveMultiplier = 22.8,
            description = "Ступень эволюции луксмаксинга #23. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 23: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 23/100, PSL 6.8"
        ),
        EvolutionStageInfo(
            stage = 24,
            nameRu = "Коч Братан (Street Mogger) • Фаза 5",
            subtitleRu = "Stage 24: PSL 6.9",
            pslScore = 6.9,
            reqAura = 11790046.0,
            clickMultiplier = 39.2,
            passiveMultiplier = 24.4,
            description = "Ступень эволюции луксмаксинга #24. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 24: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 24/100, PSL 6.9"
        ),
        EvolutionStageInfo(
            stage = 25,
            nameRu = "Берсерк Боунсмэша",
            subtitleRu = "Stage 25: PSL 7.0",
            pslScore = 7.0,
            reqAura = 15000000.0,
            clickMultiplier = 42.0,
            passiveMultiplier = 26.0,
            description = "Ступень эволюции луксмаксинга #25. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 25: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 25/100, PSL 7.0"
        ),
        EvolutionStageInfo(
            stage = 26,
            nameRu = "Берсерк Боунсмэша • Фаза 2",
            subtitleRu = "Stage 26: PSL 7.06",
            pslScore = 7.06,
            reqAura = 19083895.0,
            clickMultiplier = 45.6,
            passiveMultiplier = 28.4,
            description = "Ступень эволюции луксмаксинга #26. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 26: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 26/100, PSL 7.06"
        ),
        EvolutionStageInfo(
            stage = 27,
            nameRu = "Берсерк Боунсмэша • Фаза 3",
            subtitleRu = "Stage 27: PSL 7.12",
            pslScore = 7.12,
            reqAura = 24279669.0,
            clickMultiplier = 49.2,
            passiveMultiplier = 30.8,
            description = "Ступень эволюции луксмаксинга #27. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 27: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 27/100, PSL 7.12"
        ),
        EvolutionStageInfo(
            stage = 28,
            nameRu = "Берсерк Боунсмэша • Фаза 4",
            subtitleRu = "Stage 28: PSL 7.18",
            pslScore = 7.18,
            reqAura = 30890043.0,
            clickMultiplier = 52.8,
            passiveMultiplier = 33.2,
            description = "Ступень эволюции луксмаксинга #28. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 28: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 28/100, PSL 7.18"
        ),
        EvolutionStageInfo(
            stage = 29,
            nameRu = "Берсерк Боунсмэша • Фаза 5",
            subtitleRu = "Stage 29: PSL 7.24",
            pslScore = 7.24,
            reqAura = 39300154.0,
            clickMultiplier = 56.4,
            passiveMultiplier = 35.6,
            description = "Ступень эволюции луксмаксинга #29. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 29: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 29/100, PSL 7.24"
        ),
        EvolutionStageInfo(
            stage = 30,
            nameRu = "Сигма Офник с Района",
            subtitleRu = "Stage 30: PSL 7.3",
            pslScore = 7.3,
            reqAura = 50000000.0,
            clickMultiplier = 60.0,
            passiveMultiplier = 38.0,
            description = "Ступень эволюции луксмаксинга #30. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 30: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 30/100, PSL 7.3"
        ),
        EvolutionStageInfo(
            stage = 31,
            nameRu = "Сигма Офник с Района • Фаза 2",
            subtitleRu = "Stage 31: PSL 7.36",
            pslScore = 7.36,
            reqAura = 64599700.0,
            clickMultiplier = 66.0,
            passiveMultiplier = 41.4,
            description = "Ступень эволюции луксмаксинга #31. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 31: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 31/100, PSL 7.36"
        ),
        EvolutionStageInfo(
            stage = 32,
            nameRu = "Сигма Офник с Района • Фаза 3",
            subtitleRu = "Stage 32: PSL 7.42",
            pslScore = 7.42,
            reqAura = 83462426.0,
            clickMultiplier = 72.0,
            passiveMultiplier = 44.8,
            description = "Ступень эволюции луксмаксинга #32. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 32: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 32/100, PSL 7.42"
        ),
        EvolutionStageInfo(
            stage = 33,
            nameRu = "Сигма Офник с Района • Фаза 4",
            subtitleRu = "Stage 33: PSL 7.48",
            pslScore = 7.48,
            reqAura = 107832955.0,
            clickMultiplier = 78.0,
            passiveMultiplier = 48.2,
            description = "Ступень эволюции луксмаксинга #33. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 33: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 33/100, PSL 7.48"
        ),
        EvolutionStageInfo(
            stage = 34,
            nameRu = "Сигма Офник с Района • Фаза 5",
            subtitleRu = "Stage 34: PSL 7.54",
            pslScore = 7.54,
            reqAura = 139319531.0,
            clickMultiplier = 84.0,
            passiveMultiplier = 51.6,
            description = "Ступень эволюции луксмаксинга #34. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 34: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 34/100, PSL 7.54"
        ),
        EvolutionStageInfo(
            stage = 35,
            nameRu = "Ресейл Магнат Дубая",
            subtitleRu = "Stage 35: PSL 7.6",
            pslScore = 7.6,
            reqAura = 180000000.0,
            clickMultiplier = 90.0,
            passiveMultiplier = 55.0,
            description = "Ступень эволюции луксмаксинга #35. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 35: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 35/100, PSL 7.6"
        ),
        EvolutionStageInfo(
            stage = 36,
            nameRu = "Ресейл Магнат Дубая • Фаза 2",
            subtitleRu = "Stage 36: PSL 7.66",
            pslScore = 7.66,
            reqAura = 229006735.0,
            clickMultiplier = 98.0,
            passiveMultiplier = 60.0,
            description = "Ступень эволюции луксмаксинга #36. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 36: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 36/100, PSL 7.66"
        ),
        EvolutionStageInfo(
            stage = 37,
            nameRu = "Ресейл Магнат Дубая • Фаза 3",
            subtitleRu = "Stage 37: PSL 7.72",
            pslScore = 7.72,
            reqAura = 291356025.0,
            clickMultiplier = 106.0,
            passiveMultiplier = 65.0,
            description = "Ступень эволюции луксмаксинга #37. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 37: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 37/100, PSL 7.72"
        ),
        EvolutionStageInfo(
            stage = 38,
            nameRu = "Ресейл Магнат Дубая • Фаза 4",
            subtitleRu = "Stage 38: PSL 7.78",
            pslScore = 7.78,
            reqAura = 370680510.0,
            clickMultiplier = 114.0,
            passiveMultiplier = 70.0,
            description = "Ступень эволюции луксмаксинга #38. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 38: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 38/100, PSL 7.78"
        ),
        EvolutionStageInfo(
            stage = 39,
            nameRu = "Ресейл Магнат Дубая • Фаза 5",
            subtitleRu = "Stage 39: PSL 7.84",
            pslScore = 7.84,
            reqAura = 471601851.0,
            clickMultiplier = 122.0,
            passiveMultiplier = 75.0,
            description = "Ступень эволюции луксмаксинга #39. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 39: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 39/100, PSL 7.84"
        ),
        EvolutionStageInfo(
            stage = 40,
            nameRu = "Алмазный Чизел-Лорд",
            subtitleRu = "Stage 40: PSL 7.9",
            pslScore = 7.9,
            reqAura = 600000000.0,
            clickMultiplier = 130.0,
            passiveMultiplier = 80.0,
            description = "Ступень эволюции луксмаксинга #40. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 40: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 40/100, PSL 7.9"
        ),
        EvolutionStageInfo(
            stage = 41,
            nameRu = "Алмазный Чизел-Лорд • Фаза 2",
            subtitleRu = "Stage 41: PSL 7.96",
            pslScore = 7.96,
            reqAura = 763355782.0,
            clickMultiplier = 142.0,
            passiveMultiplier = 87.0,
            description = "Ступень эволюции луксмаксинга #41. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 41: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 41/100, PSL 7.96"
        ),
        EvolutionStageInfo(
            stage = 42,
            nameRu = "Алмазный Чизел-Лорд • Фаза 3",
            subtitleRu = "Stage 42: PSL 8.02",
            pslScore = 8.02,
            reqAura = 971186750.0,
            clickMultiplier = 154.0,
            passiveMultiplier = 94.0,
            description = "Ступень эволюции луксмаксинга #42. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 42: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 42/100, PSL 8.02"
        ),
        EvolutionStageInfo(
            stage = 43,
            nameRu = "Алмазный Чизел-Лорд • Фаза 4",
            subtitleRu = "Stage 43: PSL 8.08",
            pslScore = 8.08,
            reqAura = 1235601701.0,
            clickMultiplier = 166.0,
            passiveMultiplier = 101.0,
            description = "Ступень эволюции луксмаксинга #43. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 43: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 43/100, PSL 8.08"
        ),
        EvolutionStageInfo(
            stage = 44,
            nameRu = "Алмазный Чизел-Лорд • Фаза 5",
            subtitleRu = "Stage 44: PSL 8.14",
            pslScore = 8.14,
            reqAura = 1572006171.0,
            clickMultiplier = 178.0,
            passiveMultiplier = 108.0,
            description = "Ступень эволюции луксмаксинга #44. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 44: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 44/100, PSL 8.14"
        ),
        EvolutionStageInfo(
            stage = 45,
            nameRu = "Тёмщик на М5 F90",
            subtitleRu = "Stage 45: PSL 8.2",
            pslScore = 8.2,
            reqAura = 2000000000.0,
            clickMultiplier = 190.0,
            passiveMultiplier = 115.0,
            description = "Ступень эволюции луксмаксинга #45. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 45: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 45/100, PSL 8.2"
        ),
        EvolutionStageInfo(
            stage = 46,
            nameRu = "Тёмщик на М5 F90 • Фаза 2",
            subtitleRu = "Stage 46: PSL 8.26",
            pslScore = 8.26,
            reqAura = 2531667508.0,
            clickMultiplier = 206.0,
            passiveMultiplier = 124.0,
            description = "Ступень эволюции луксмаксинга #46. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 46: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 46/100, PSL 8.26"
        ),
        EvolutionStageInfo(
            stage = 47,
            nameRu = "Тёмщик на М5 F90 • Фаза 3",
            subtitleRu = "Stage 47: PSL 8.32",
            pslScore = 8.32,
            reqAura = 3204670186.0,
            clickMultiplier = 222.0,
            passiveMultiplier = 133.0,
            description = "Ступень эволюции луксмаксинга #47. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 47: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 47/100, PSL 8.32"
        ),
        EvolutionStageInfo(
            stage = 48,
            nameRu = "Тёмщик на М5 F90 • Фаза 4",
            subtitleRu = "Stage 48: PSL 8.38",
            pslScore = 8.38,
            reqAura = 4056579693.0,
            clickMultiplier = 238.0,
            passiveMultiplier = 142.0,
            description = "Ступень эволюции луксмаксинга #48. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 48: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 48/100, PSL 8.38"
        ),
        EvolutionStageInfo(
            stage = 49,
            nameRu = "Тёмщик на М5 F90 • Фаза 5",
            subtitleRu = "Stage 49: PSL 8.44",
            pslScore = 8.44,
            reqAura = 5134955502.0,
            clickMultiplier = 254.0,
            passiveMultiplier = 151.0,
            description = "Ступень эволюции луксмаксинга #49. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 49: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 49/100, PSL 8.44"
        ),
        EvolutionStageInfo(
            stage = 50,
            nameRu = "Гигачад Император",
            subtitleRu = "Stage 50: PSL 8.5",
            pslScore = 8.5,
            reqAura = 6500000000.0,
            clickMultiplier = 270.0,
            passiveMultiplier = 160.0,
            description = "Ступень эволюции луксмаксинга #50. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 50: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 50/100, PSL 8.5"
        ),
        EvolutionStageInfo(
            stage = 51,
            nameRu = "Гигачад Император • Фаза 2",
            subtitleRu = "Stage 51: PSL 8.54",
            pslScore = 8.54,
            reqAura = 8138356018.0,
            clickMultiplier = 292.0,
            passiveMultiplier = 172.0,
            description = "Ступень эволюции луксмаксинга #51. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 51: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 51/100, PSL 8.54"
        ),
        EvolutionStageInfo(
            stage = 52,
            nameRu = "Гигачад Император • Фаза 3",
            subtitleRu = "Stage 52: PSL 8.58",
            pslScore = 8.58,
            reqAura = 10189667489.0,
            clickMultiplier = 314.0,
            passiveMultiplier = 184.0,
            description = "Ступень эволюции луксмаксинга #52. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 52: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 52/100, PSL 8.58"
        ),
        EvolutionStageInfo(
            stage = 53,
            nameRu = "Гигачад Император • Фаза 4",
            subtitleRu = "Stage 53: PSL 8.62",
            pslScore = 8.62,
            reqAura = 12758021804.0,
            clickMultiplier = 336.0,
            passiveMultiplier = 196.0,
            description = "Ступень эволюции луксмаксинга #53. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 53: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 53/100, PSL 8.62"
        ),
        EvolutionStageInfo(
            stage = 54,
            nameRu = "Гигачад Император • Фаза 5",
            subtitleRu = "Stage 54: PSL 8.66",
            pslScore = 8.66,
            reqAura = 15973742082.0,
            clickMultiplier = 358.0,
            passiveMultiplier = 208.0,
            description = "Ступень эволюции луксмаксинга #54. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 54: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 54/100, PSL 8.66"
        ),
        EvolutionStageInfo(
            stage = 55,
            nameRu = "Банный Сигма-Титан 110°C",
            subtitleRu = "Stage 55: PSL 8.7",
            pslScore = 8.7,
            reqAura = 20000000000.0,
            clickMultiplier = 380.0,
            passiveMultiplier = 220.0,
            description = "Ступень эволюции луксмаксинга #55. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 55: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 55/100, PSL 8.7"
        ),
        EvolutionStageInfo(
            stage = 56,
            nameRu = "Банный Сигма-Титан 110°C • Фаза 2",
            subtitleRu = "Stage 56: PSL 8.74",
            pslScore = 8.74,
            reqAura = 24914618792.0,
            clickMultiplier = 408.0,
            passiveMultiplier = 236.0,
            description = "Ступень эволюции луксмаксинга #56. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 56: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 56/100, PSL 8.74"
        ),
        EvolutionStageInfo(
            stage = 57,
            nameRu = "Банный Сигма-Титан 110°C • Фаза 3",
            subtitleRu = "Stage 57: PSL 8.78",
            pslScore = 8.78,
            reqAura = 31036911478.0,
            clickMultiplier = 436.0,
            passiveMultiplier = 252.0,
            description = "Ступень эволюции луксмаксинга #57. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 57: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 57/100, PSL 8.78"
        ),
        EvolutionStageInfo(
            stage = 58,
            nameRu = "Банный Сигма-Титан 110°C • Фаза 4",
            subtitleRu = "Stage 58: PSL 8.82",
            pslScore = 8.82,
            reqAura = 38663640899.0,
            clickMultiplier = 464.0,
            passiveMultiplier = 268.0,
            description = "Ступень эволюции луксмаксинга #58. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 58: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 58/100, PSL 8.82"
        ),
        EvolutionStageInfo(
            stage = 59,
            nameRu = "Банный Сигма-Титан 110°C • Фаза 5",
            subtitleRu = "Stage 59: PSL 8.86",
            pslScore = 8.86,
            reqAura = 48164493706.0,
            clickMultiplier = 492.0,
            passiveMultiplier = 284.0,
            description = "Ступень эволюции луксмаксинга #59. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 59: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 59/100, PSL 8.86"
        ),
        EvolutionStageInfo(
            stage = 60,
            nameRu = "Кумысный Батыр Ханства",
            subtitleRu = "Stage 60: PSL 8.9",
            pslScore = 8.9,
            reqAura = 60000000000.0,
            clickMultiplier = 520.0,
            passiveMultiplier = 300.0,
            description = "Ступень эволюции луксмаксинга #60. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 60: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 60/100, PSL 8.9"
        ),
        EvolutionStageInfo(
            stage = 61,
            nameRu = "Кумысный Батыр Ханства • Фаза 2",
            subtitleRu = "Stage 61: PSL 8.94",
            pslScore = 8.94,
            reqAura = 74743856377.0,
            clickMultiplier = 560.0,
            passiveMultiplier = 324.0,
            description = "Ступень эволюции луксмаксинга #61. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 61: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 61/100, PSL 8.94"
        ),
        EvolutionStageInfo(
            stage = 62,
            nameRu = "Кумысный Батыр Ханства • Фаза 3",
            subtitleRu = "Stage 62: PSL 8.98",
            pslScore = 8.98,
            reqAura = 93110734435.0,
            clickMultiplier = 600.0,
            passiveMultiplier = 348.0,
            description = "Ступень эволюции луксмаксинга #62. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 62: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 62/100, PSL 8.98"
        ),
        EvolutionStageInfo(
            stage = 63,
            nameRu = "Кумысный Батыр Ханства • Фаза 4",
            subtitleRu = "Stage 63: PSL 9.02",
            pslScore = 9.02,
            reqAura = 115990922696.0,
            clickMultiplier = 640.0,
            passiveMultiplier = 372.0,
            description = "Ступень эволюции луксмаксинга #63. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 63: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 63/100, PSL 9.02"
        ),
        EvolutionStageInfo(
            stage = 64,
            nameRu = "Кумысный Батыр Ханства • Фаза 5",
            subtitleRu = "Stage 64: PSL 9.06",
            pslScore = 9.06,
            reqAura = 144493481117.0,
            clickMultiplier = 680.0,
            passiveMultiplier = 396.0,
            description = "Ступень эволюции луксмаксинга #64. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 64: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 64/100, PSL 9.06"
        ),
        EvolutionStageInfo(
            stage = 65,
            nameRu = "Повелитель Положительного Кантуса",
            subtitleRu = "Stage 65: PSL 9.1",
            pslScore = 9.1,
            reqAura = 180000000000.0,
            clickMultiplier = 720.0,
            passiveMultiplier = 420.0,
            description = "Ступень эволюции луксмаксинга #65. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 65: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 65/100, PSL 9.1"
        ),
        EvolutionStageInfo(
            stage = 66,
            nameRu = "Повелитель Положительного Кантуса • Фаза 2",
            subtitleRu = "Stage 66: PSL 9.14",
            pslScore = 9.14,
            reqAura = 220806576845.0,
            clickMultiplier = 776.0,
            passiveMultiplier = 456.0,
            description = "Ступень эволюции луксмаксинга #66. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 66: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 66/100, PSL 9.14"
        ),
        EvolutionStageInfo(
            stage = 67,
            nameRu = "Повелитель Положительного Кантуса • Фаза 3",
            subtitleRu = "Stage 67: PSL 9.18",
            pslScore = 9.18,
            reqAura = 270864135434.0,
            clickMultiplier = 832.0,
            passiveMultiplier = 492.0,
            description = "Ступень эволюции луксмаксинга #67. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 67: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 67/100, PSL 9.18"
        ),
        EvolutionStageInfo(
            stage = 68,
            nameRu = "Повелитель Положительного Кантуса • Фаза 4",
            subtitleRu = "Stage 68: PSL 9.22",
            pslScore = 9.22,
            reqAura = 332269902974.0,
            clickMultiplier = 888.0,
            passiveMultiplier = 528.0,
            description = "Ступень эволюции луксмаксинга #68. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 68: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 68/100, PSL 9.22"
        ),
        EvolutionStageInfo(
            stage = 69,
            nameRu = "Повелитель Положительного Кантуса • Фаза 5",
            subtitleRu = "Stage 69: PSL 9.26",
            pslScore = 9.26,
            reqAura = 407596554803.0,
            clickMultiplier = 944.0,
            passiveMultiplier = 564.0,
            description = "Ступень эволюции луксмаксинга #69. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 69: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 69/100, PSL 9.26"
        ),
        EvolutionStageInfo(
            stage = 70,
            nameRu = "Квантовый Архитектор Черепа",
            subtitleRu = "Stage 70: PSL 9.3",
            pslScore = 9.3,
            reqAura = 500000000000.0,
            clickMultiplier = 1000.0,
            passiveMultiplier = 600.0,
            description = "Ступень эволюции луксмаксинга #70. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 70: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 70/100, PSL 9.3"
        ),
        EvolutionStageInfo(
            stage = 71,
            nameRu = "Квантовый Архитектор Черепа • Фаза 2",
            subtitleRu = "Stage 71: PSL 9.34",
            pslScore = 9.34,
            reqAura = 622865469808.0,
            clickMultiplier = 1080.0,
            passiveMultiplier = 650.0,
            description = "Ступень эволюции луксмаксинга #71. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 71: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 71/100, PSL 9.34"
        ),
        EvolutionStageInfo(
            stage = 72,
            nameRu = "Квантовый Архитектор Черепа • Фаза 3",
            subtitleRu = "Stage 72: PSL 9.38",
            pslScore = 9.38,
            reqAura = 775922786958.0,
            clickMultiplier = 1160.0,
            passiveMultiplier = 700.0,
            description = "Ступень эволюции луксмаксинга #72. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 72: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 72/100, PSL 9.38"
        ),
        EvolutionStageInfo(
            stage = 73,
            nameRu = "Квантовый Архитектор Черепа • Фаза 4",
            subtitleRu = "Stage 73: PSL 9.42",
            pslScore = 9.42,
            reqAura = 966591022466.0,
            clickMultiplier = 1240.0,
            passiveMultiplier = 750.0,
            description = "Ступень эволюции луксмаксинга #73. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 73: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 73/100, PSL 9.42"
        ),
        EvolutionStageInfo(
            stage = 74,
            nameRu = "Квантовый Архитектор Черепа • Фаза 5",
            subtitleRu = "Stage 74: PSL 9.46",
            pslScore = 9.46,
            reqAura = 1204112342640.0,
            clickMultiplier = 1320.0,
            passiveMultiplier = 800.0,
            description = "Ступень эволюции луксмаксинга #74. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 74: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 74/100, PSL 9.46"
        ),
        EvolutionStageInfo(
            stage = 75,
            nameRu = "Гиперборейский Полубог",
            subtitleRu = "Stage 75: PSL 9.5",
            pslScore = 9.5,
            reqAura = 1500000000000.0,
            clickMultiplier = 1400.0,
            passiveMultiplier = 850.0,
            description = "Ступень эволюции луксмаксинга #75. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 75: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 75/100, PSL 9.5"
        ),
        EvolutionStageInfo(
            stage = 76,
            nameRu = "Гиперборейский Полубог • Фаза 2",
            subtitleRu = "Stage 76: PSL 9.52",
            pslScore = 9.52,
            reqAura = 1868596409423.0,
            clickMultiplier = 1500.0,
            passiveMultiplier = 920.0,
            description = "Ступень эволюции луксмаксинга #76. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 76: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 76/100, PSL 9.52"
        ),
        EvolutionStageInfo(
            stage = 77,
            nameRu = "Гиперборейский Полубог • Фаза 3",
            subtitleRu = "Stage 77: PSL 9.54",
            pslScore = 9.54,
            reqAura = 2327768360873.0,
            clickMultiplier = 1600.0,
            passiveMultiplier = 990.0,
            description = "Ступень эволюции луксмаксинга #77. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 77: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 77/100, PSL 9.54"
        ),
        EvolutionStageInfo(
            stage = 78,
            nameRu = "Гиперборейский Полубог • Фаза 4",
            subtitleRu = "Stage 78: PSL 9.56",
            pslScore = 9.56,
            reqAura = 2899773067398.0,
            clickMultiplier = 1700.0,
            passiveMultiplier = 1060.0,
            description = "Ступень эволюции луксмаксинга #78. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 78: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 78/100, PSL 9.56"
        ),
        EvolutionStageInfo(
            stage = 79,
            nameRu = "Гиперборейский Полубог • Фаза 5",
            subtitleRu = "Stage 79: PSL 9.58",
            pslScore = 9.58,
            reqAura = 3612337027921.0,
            clickMultiplier = 1800.0,
            passiveMultiplier = 1130.0,
            description = "Ступень эволюции луксмаксинга #79. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 79: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 79/100, PSL 9.58"
        ),
        EvolutionStageInfo(
            stage = 80,
            nameRu = "Галактический Моггер Планет",
            subtitleRu = "Stage 80: PSL 9.6",
            pslScore = 9.6,
            reqAura = 4500000000000.0,
            clickMultiplier = 1900.0,
            passiveMultiplier = 1200.0,
            description = "Ступень эволюции луксмаксинга #80. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 80: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 80/100, PSL 9.6"
        ),
        EvolutionStageInfo(
            stage = 81,
            nameRu = "Галактический Моггер Планет • Фаза 2",
            subtitleRu = "Stage 81: PSL 9.62",
            pslScore = 9.62,
            reqAura = 5475279077039.0,
            clickMultiplier = 2020.0,
            passiveMultiplier = 1280.0,
            description = "Ступень эволюции луксмаксинга #81. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 81: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 81/100, PSL 9.62"
        ),
        EvolutionStageInfo(
            stage = 82,
            nameRu = "Галактический Моггер Планет • Фаза 3",
            subtitleRu = "Stage 82: PSL 9.64",
            pslScore = 9.64,
            reqAura = 6661929104769.0,
            clickMultiplier = 2140.0,
            passiveMultiplier = 1360.0,
            description = "Ступень эволюции луксмаксинга #82. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 82: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 82/100, PSL 9.64"
        ),
        EvolutionStageInfo(
            stage = 83,
            nameRu = "Галактический Моггер Планет • Фаза 4",
            subtitleRu = "Stage 83: PSL 9.66",
            pslScore = 9.66,
            reqAura = 8105760231124.0,
            clickMultiplier = 2260.0,
            passiveMultiplier = 1440.0,
            description = "Ступень эволюции луксмаксинга #83. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 83: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 83/100, PSL 9.66"
        ),
        EvolutionStageInfo(
            stage = 84,
            nameRu = "Галактический Моггер Планет • Фаза 5",
            subtitleRu = "Stage 84: PSL 9.68",
            pslScore = 9.68,
            reqAura = 9862510977103.0,
            clickMultiplier = 2380.0,
            passiveMultiplier = 1520.0,
            description = "Ступень эволюции луксмаксинга #84. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 84: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 84/100, PSL 9.68"
        ),
        EvolutionStageInfo(
            stage = 85,
            nameRu = "Разрушитель Биологических Ограничений",
            subtitleRu = "Stage 85: PSL 9.7",
            pslScore = 9.7,
            reqAura = 12000000000000.0,
            clickMultiplier = 2500.0,
            passiveMultiplier = 1600.0,
            description = "Ступень эволюции луксмаксинга #85. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 85: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 85/100, PSL 9.7"
        ),
        EvolutionStageInfo(
            stage = 86,
            nameRu = "Разрушитель Биологических Ограничений • Фаза 2",
            subtitleRu = "Stage 86: PSL 9.72",
            pslScore = 9.72,
            reqAura = 14413493207777.0,
            clickMultiplier = 2640.0,
            passiveMultiplier = 1700.0,
            description = "Ступень эволюции луксмаксинга #86. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 86: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 86/100, PSL 9.72"
        ),
        EvolutionStageInfo(
            stage = 87,
            nameRu = "Разрушитель Биологических Ограничений • Фаза 3",
            subtitleRu = "Stage 87: PSL 9.74",
            pslScore = 9.74,
            reqAura = 17312398870887.0,
            clickMultiplier = 2780.0,
            passiveMultiplier = 1800.0,
            description = "Ступень эволюции луксмаксинга #87. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 87: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 87/100, PSL 9.74"
        ),
        EvolutionStageInfo(
            stage = 88,
            nameRu = "Разрушитель Биологических Ограничений • Фаза 4",
            subtitleRu = "Stage 88: PSL 9.76",
            pslScore = 9.76,
            reqAura = 20794345294654.0,
            clickMultiplier = 2920.0,
            passiveMultiplier = 1900.0,
            description = "Ступень эволюции луксмаксинга #88. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 88: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 88/100, PSL 9.76"
        ),
        EvolutionStageInfo(
            stage = 89,
            nameRu = "Разрушитель Биологических Ограничений • Фаза 5",
            subtitleRu = "Stage 89: PSL 9.78",
            pslScore = 9.78,
            reqAura = 24976596222056.0,
            clickMultiplier = 3060.0,
            passiveMultiplier = 2000.0,
            description = "Ступень эволюции луксмаксинга #89. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 89: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 89/100, PSL 9.78"
        ),
        EvolutionStageInfo(
            stage = 90,
            nameRu = "Владыка Вселенского Мьюинга",
            subtitleRu = "Stage 90: PSL 9.8",
            pslScore = 9.8,
            reqAura = 30000000000000.0,
            clickMultiplier = 3200.0,
            passiveMultiplier = 2100.0,
            description = "Ступень эволюции луксмаксинга #90. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 90: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 90/100, PSL 9.8"
        ),
        EvolutionStageInfo(
            stage = 91,
            nameRu = "Владыка Вселенского Мьюинга • Фаза 2",
            subtitleRu = "Stage 91: PSL 9.82",
            pslScore = 9.82,
            reqAura = 35539933576267.0,
            clickMultiplier = 3360.0,
            passiveMultiplier = 2220.0,
            description = "Ступень эволюции луксмаксинга #91. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 91: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 91/100, PSL 9.82"
        ),
        EvolutionStageInfo(
            stage = 92,
            nameRu = "Владыка Вселенского Мьюинга • Фаза 3",
            subtitleRu = "Stage 92: PSL 9.84",
            pslScore = 9.84,
            reqAura = 42102895953516.0,
            clickMultiplier = 3520.0,
            passiveMultiplier = 2340.0,
            description = "Ступень эволюции луксмаксинга #92. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 92: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 92/100, PSL 9.84"
        ),
        EvolutionStageInfo(
            stage = 93,
            nameRu = "Владыка Вселенского Мьюинга • Фаза 4",
            subtitleRu = "Stage 93: PSL 9.86",
            pslScore = 9.86,
            reqAura = 49877804185216.0,
            clickMultiplier = 3680.0,
            passiveMultiplier = 2460.0,
            description = "Ступень эволюции луксмаксинга #93. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 93: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 93/100, PSL 9.86"
        ),
        EvolutionStageInfo(
            stage = 94,
            nameRu = "Владыка Вселенского Мьюинга • Фаза 5",
            subtitleRu = "Stage 94: PSL 9.88",
            pslScore = 9.88,
            reqAura = 59088461589088.0,
            clickMultiplier = 3840.0,
            passiveMultiplier = 2580.0,
            description = "Ступень эволюции луксмаксинга #94. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 94: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 94/100, PSL 9.88"
        ),
        EvolutionStageInfo(
            stage = 95,
            nameRu = "Сингулярность Идеальных Скул",
            subtitleRu = "Stage 95: PSL 9.9",
            pslScore = 9.9,
            reqAura = 70000000000000.0,
            clickMultiplier = 4000.0,
            passiveMultiplier = 2700.0,
            description = "Ступень эволюции луксмаксинга #95. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 95: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 95/100, PSL 9.9"
        ),
        EvolutionStageInfo(
            stage = 96,
            nameRu = "Сингулярность Идеальных Скул • Фаза 2",
            subtitleRu = "Stage 96: PSL 9.92",
            pslScore = 9.92,
            reqAura = 81526103104576.0,
            clickMultiplier = 4200.0,
            passiveMultiplier = 2860.0,
            description = "Ступень эволюции луксмаксинга #96. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 96: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 96/100, PSL 9.92"
        ),
        EvolutionStageInfo(
            stage = 97,
            nameRu = "Сингулярность Идеальных Скул • Фаза 3",
            subtitleRu = "Stage 97: PSL 9.94",
            pslScore = 9.94,
            reqAura = 94950078391685.0,
            clickMultiplier = 4400.0,
            passiveMultiplier = 3020.0,
            description = "Ступень эволюции луксмаксинга #97. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 97: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 97/100, PSL 9.94"
        ),
        EvolutionStageInfo(
            stage = 98,
            nameRu = "Сингулярность Идеальных Скул • Фаза 4",
            subtitleRu = "Stage 98: PSL 9.96",
            pslScore = 9.96,
            reqAura = 110584426867830.0,
            clickMultiplier = 4600.0,
            passiveMultiplier = 3180.0,
            description = "Ступень эволюции луксмаксинга #98. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 98: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 98/100, PSL 9.96"
        ),
        EvolutionStageInfo(
            stage = 99,
            nameRu = "Сингулярность Идеальных Скул • Фаза 5",
            subtitleRu = "Stage 99: PSL 9.98",
            pslScore = 9.98,
            reqAura = 128793105522673.0,
            clickMultiplier = 4800.0,
            passiveMultiplier = 3340.0,
            description = "Ступень эволюции луксмаксинга #99. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 99: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 99/100, PSL 9.98"
        ),
        EvolutionStageInfo(
            stage = 100,
            nameRu = "Абсолютный Бог Мультивселенной Луксмакса",
            subtitleRu = "Stage 100: PSL 10.0",
            pslScore = 10.0,
            reqAura = 150000000000000.0,
            clickMultiplier = 5000.0,
            passiveMultiplier = 3500.0,
            description = "Ступень эволюции луксмаксинга #100. Гониальный угол совершенствуется.",
            memeQuote = "«Этап 100: челюсть режет пространство-время.»",
            profileFeature = "Уровень челюсти 100/100, PSL 10.0"
        ),
    )

    fun getStage(stage: Int): EvolutionStageInfo {
        return STAGES.getOrElse(stage.coerceIn(0, STAGES.lastIndex)) { STAGES.last() }
    }
}
